# Generated by Django 4.2.7 on 2025-09-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='message_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='response_notes_ar',
            field=models.TextField(blank=True, help_text='Internal notes about response', null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='response_notes_en',
            field=models.TextField(blank=True, help_text='Internal notes about response', null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='subject_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='subject_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
