# Generated by Django 4.2.7 on 2025-09-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('client_type', models.CharField(help_text="Anonymized client type (e.g., 'University Student', 'Graduate Researcher')", max_length=100)),
                ('completion_date', models.DateField()),
                ('technologies_used', models.JSONField(default=list, help_text='List of technologies or tools used')),
                ('technologies_used_en', models.JSONField(default=list, help_text='List of technologies or tools used', null=True)),
                ('technologies_used_ar', models.JSONField(default=list, help_text='List of technologies or tools used', null=True)),
                ('project_duration', models.CharField(blank=True, help_text="e.g., '2 weeks', '1 month'", max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Display in featured portfolio section')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-is_featured', 'order', '-completion_date'],
            },
        ),
    ]
